import pandas as pd
basket_details = pd.read_csv('/Users/yaotian/Desktop/Project-2/basket_details.csv')
customer_details = pd.read_csv('/Users/yaotian/Desktop/Project-2/customer_details.csv')
print("Basket Details Info:")
print(basket_details.info())
print(basket_details.head())
print("\nCustomer Details Info:")
print(customer_details.info())
print(customer_details.head())
basket_details['basket_date'] = pd.to_datetime(basket_details['basket_date'])
merged_data = pd.merge(basket_details, customer_details, on='customer_id', how='inner')
print("Merged Data Info:")
print(merged_data.info())
print(merged_data.head())
product_sales = merged_data.groupby('product_id')['basket_count'].sum().sort_values(ascending=False)
print("Top 5 Best-Selling Products:")
print(product_sales.head(5))
gender_sales = merged_data.groupby('sex')['basket_count'].sum()
print("Sales by Gender")
print(gender_sales)
import matplotlib.pyplot as plt
merged_data['month'] = merged_data['basket_date'].dt.to_period('M')
monthly_sales = merged_data.groupby('month')['basket_count'].sum()
print("Monthly Sales:")
print(monthly_sales)
plt.figure(figsize=(12, 6))
monthly_sales.plot(kind='line', marker='o')
plt.title('Monthly Sales Trend', fontsize=16)
plt.xlabel('Month', fontsize=12)
plt.ylabel('Total Sales', fontsize=12)
plt.grid()
plt.show()

